config/routes.rb
Rails.application.routes.draw do 
  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true
  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new( publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
                                   secret_token: Rails.application.credentials.iex_client[:secret_access_key],
                                   endpoint: 'https://sandbox.iexapis.com/v1')
    begin
      new(ticker:ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol) )
    rescue => exception
      return nil
    end
  end

  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?    
  end
  
  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    def search
      if params[:stock].present?
        @stock = Stock.new_lookup(params[:stock])
        if @stock
          respond_to do |format|
            format.js { render partial: 'users/results'}
          end
        else
          respond_to do |format|
            flash.now[:alert] = "Please enter a valid symbol to search"
            format.js { render partial: 'users/results'}
          end
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Please enter a symbol to search"
          format.js { render partial: 'users/results'}
        end
      end
    end
  end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
    def create
        stock = Stock.check_db(params[:ticker])
        if stock.blank?
          stock = Stock.new_lookup(params[:ticker])
          stock.save
        end  
        @user_stock = UserStock.create(user: current_user, stock: stock)
        flash[:notice] = "Stock #{stock.name} was successfully added to your portfolio"
        redirect_to my_portfolio_path
    end
    
    def destroy
        stock = Stock.find(params[:id])
        user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
        user_stock.destroy
        flash[:notice] = "#{stock.ticker} was successfully removed from portfolio"
        redirect_to my_portfolio_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @tracked_Stocks = current_user.stocks 
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg|%>
  <% if name == "notice" %>
    <div class="alert alert-success message_box alert-dismissible fade show"> 
      <%= msg %> 
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% else %>
    <div class="alert alert-danger message_box alert-dismissible fade show"> 
      <%= msg %> 
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'FinanceTracker', root_path, class: 'navbar-brand' %>
    <% if current_user %> 
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item active <%= 'active' if request.path == my_portfolio_path %>">
            <%= link_to 'My Portfolio', my_portfolio_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'My Friends', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.full_name %> <%= fa_icon 'user' %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to edit_user_registration_path, class: 'dropdown-item' do %>
                <%= fa_icon 'edit' %> Edit profile
              <% end %>
              <li><hr class="dropdown-divider"></li>
              <%= link_to("Logout", destroy_user_session_path, class: "btn logout-button", method: :delete)%>
            </ul>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container text-center">
      <%= render 'layouts/messages'  %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<% if !@tracked_Stocks.empty? %>
  <table class="table table-striped table-hover table-bordered mt-3">
    <thead>
      <tr>
        <th scope="col">Ticker</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @tracked_Stocks.each do |stock| %>
        <tr>
          <th scope="row"> <%= stock.ticker %> </th>
          <td> <%= stock.name %> </td>
          <td> <%= stock.last_price %> </td>
          <td> <%= link_to 'Remove', user_stock_path(stock), method: :delete, data: {confirm: 'Are you sure?'},
          class: 'btn btn-sm btn-warning' %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>  
<% end %>

app/views/users/_results.html.erb
<%= render 'layouts/messages' %>
<% if @stock %>
  <div class="card card-header results-block"> 
    <strong>Symbol: </strong> <%= @stock.ticker%>
    <strong>Name: </strong> <%= @stock.name%>
    <strong>Price: </strong> <%= @stock.last_price%>
    <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker), class: "btn btn-sm btn-success", method: :post %>
    <% else %>
      <span class="badge bg-secondary">
        You are already tracking
        <% if !current_user.under_stock_limit? %>
          10 stocks
        <% end %>
        <% if current_user.stock_already_tracked?(@stock.ticker) %>
          this stock
        <% end %>
      </span>
    <% end %>
  </div>
<% end %>

app/views/users/_results.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'users/results.html'%>'

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class="search-area" id="centralized_content">
  <h2>Search Stocks</h2>
  
  <%= form_tag search_stock_path, remote: true ,method: :get do %>
    <div class="form-goup row pt-3">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
  <div id="results"></div>

  <%= render 'stocks/list' %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to the Finance Tracker app</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= link_to 'Sing out', destroy_user_session_path, method: :delete%>